# Site settings
title: "achntrl"
header-img: img/home-bg.jpg
email: alexandre@achntrl.com
description: "Alexandre Chaintreuil - Software engineer at Datadog."
baseurl: ""
url: "http://www.achntrl.com"
twitter_username: achntrl
github_username:  achntrl
linkedin_username: alexandrechaintreuil
author: Alexandre Chaintreuil

# Build settings
plugins: [jekyll-paginate, jekyll-sitemap]
markdown: kramdown
# highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["node_modules","Gruntfile.js","package.json","README.md","less"]
